# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_apirequestlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermMemoryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(choices=[("nutrition", "Nutrition"), ("workout", "Workout")], max_length=30)),
                ("scope", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_key", models.CharField(max_length=255)),
                ("raw_label", models.CharField(blank=True, default="", max_length=255)),
                ("reason_code", models.CharField(blank=True, default="unknown", max_length=80)),
                ("source_action", models.CharField(blank=True, default="", max_length=80)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("hit_count", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_term_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "short_term_memory_entry",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shorttermmemoryentry",
            index=models.Index(fields=["user", "domain", "expires_at"], name="short_term__user_id_9ce312_idx"),
        ),
        migrations.AddIndex(
            model_name="shorttermmemoryentry",
            index=models.Index(fields=["user", "domain", "scope", "entity_type"], name="short_term__user_id_4e15f9_idx"),
        ),
        migrations.AddIndex(
            model_name="shorttermmemoryentry",
            index=models.Index(fields=["entity_type", "entity_key"], name="short_term__entity__38678f_idx"),
        ),
        migrations.AddConstraint(
            model_name="shorttermmemoryentry",
            constraint=models.UniqueConstraint(
                fields=("user", "domain", "scope", "entity_type", "entity_key"),
                name="uniq_short_term_memory_entity",
            ),
        ),
    ]
