# Generated by Django 5.2.13 on 2026-04-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_style', models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('low_carb', 'Low carb'), ('keto', 'Keto'), ('mediterranean', 'Mediterranean')], default='none', max_length=30)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('disliked_foods', models.JSONField(blank=True, default=list)),
                ('favorite_foods', models.JSONField(blank=True, default=list)),
                ('avoid_ingredients', models.JSONField(blank=True, default=list)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('very_active', 'Very active'), ('athlete', 'Athlete')], default='moderate', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('goal_type', models.CharField(choices=[('cut', 'Cut'), ('bulk', 'Bulk'), ('recomp', 'Recomp'), ('maintain', 'Maintain')], default='recomp', max_length=20)),
                ('goal_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
