# Generated by Django 5.2.13 on 2026-05-04 10:00

from django.db import migrations, models


def copy_latest_workout_intent_to_profile(apps, schema_editor):
    UserProfile = apps.get_model("profiles", "UserProfile")
    WorkoutIntentAnalysis = apps.get_model("workout", "WorkoutIntentAnalysis")

    for profile in UserProfile.objects.all():
        latest_intent = WorkoutIntentAnalysis.objects.filter(user_id=profile.user_id).order_by("-created_at").first()
        if latest_intent and latest_intent.focus_muscles:
            profile.focus_muscles = latest_intent.focus_muscles
            profile.save(update_fields=["focus_muscles"])


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workout', '0002_workoutintentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focus_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_latest_workout_intent_to_profile, migrations.RunPython.noop),
    ]
