# Generated by Django 5.2.9 on 2025-12-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_part_raw', models.CharField(blank=True, default='', max_length=255)),
                ('muscle_groups', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(blank=True, default='unknown', max_length=64)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
