# Generated by Django 5.2.9 on 2025-12-25 09:48

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercise_embedding_exercise_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='embedding_model',
            field=models.CharField(blank=True, default='text-embedding-3-small@1536', max_length=64),
        ),
    ]
