# Generated by Django 5.2.9 on 2026-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_exercise_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_name_vi', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('protein_animal', 'Protein Animal'), ('vegetable', 'Vegetable'), ('starchy_carb', 'Starchy Carb'), ('fruit', 'Fruit'), ('protein_plant', 'Protein Plant'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('fat_oil', 'Fat Oil'), ('condiment', 'Condiment'), ('beverage', 'Beverage'), ('supplement', 'Supplement')], max_length=32)),
                ('edible_form', models.CharField(choices=[('raw', 'Raw'), ('cooked', 'Cooked'), ('liquid', 'Liquid'), ('powder', 'Powder')], max_length=16)),
                ('kcal_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carb_g_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fat_g_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fiber_g_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sodium_mg_per_100g', models.IntegerField(default=0)),
                ('default_serving_g', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('aliases', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='manual_seed', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
