# Generated by Django 5.2.9 on 2025-12-19 03:54

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_exercise_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='embedding_model',
            field=models.CharField(blank=True, default='gemini-embedding-001@768', max_length=64),
        ),
        migrations.AddField(
            model_name='exercise',
            name='embedding_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='wk_ex_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
