# Generated by Django 5.2.13 on 2026-04-29 13:54

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body_part_raw', models.CharField(blank=True, max_length=100)),
                ('muscle_groups', models.JSONField(blank=True, default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(default='beginner', max_length=30)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.CharField(blank=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_text', models.TextField(blank=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise',
                'ordering': ['title'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='wk_ex_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
