# Generated by Django 5.2.15 on 2026-06-08 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_shorttermmemoryentry'),
        ('workout', '0002_workoutintentanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_completions', to='common.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_completion',
                'ordering': ['-workout_date'],
                'indexes': [models.Index(fields=['user', 'workout_date'], name='workout_com_user_id_ff6a03_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'workout_date'), name='uniq_workout_completion_user_date')],
            },
        ),
    ]
