# Generated by Django 5.2.13 on 2026-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=120, unique=True)),
                ('display_name_vi', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('food_role', models.CharField(max_length=100)),
                ('edible_form', models.CharField(blank=True, max_length=100)),
                ('kcal_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_g_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carb_g_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fiber_g_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium_mg_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_serving_g', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('aliases', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nutrition_atom',
                'ordering': ['canonical_name'],
            },
        ),
    ]
